import React from 'react'
import styled from "styled-components";

function Footer() {
  return (
      <>
      <section className='Contain' >
      <div className="Icon" />
      <div className="Incon" />
      <div className="Inncon" />
      </section>
      <p className='text'>Search</p>
      <p className='exp'>Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.</p>
      <p className='text1'>Search</p>
      <p className='exp1'> Choose from thousands of options generated by the slogan maker that fit your needs</p>
      <p className='text2'>Stand Out</p>
      <p className='exp2'>Congrats on your new slogan. It's time to win the world!</p>
      </>
      
      
      
    )
}


export default Footer